project_name: diskusage

version: 2
# Basic goreleaser configuration for cross-building diskusage
# Produces tar.gz archives for linux/darwin/windows on amd64 and arm64.

builds:
  - id: diskusage
    main: ./
    binary: diskusage
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - diskusage{{ if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: "git"

release:
  github:
    owner: "kim-groenborg-nielsen"
    name: "diskusage"
